services:
    geo-db:
      image: postgis/postgis:14-3.2
      environment:
        POSTGRES_USER: ${DB_USER:-user}
        POSTGRES_DB: ${DB_NAME:-geo-db}
        POSTGRES_PASSWORD: ${DB_PASS:-267}
      ports:
        - '${DB_PORT:-5432}:5432'
      volumes:
        - db-data:/var/lib/postgresql/data

volumes:
  db-data: